#!/bin/bash

function createUniversity() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/university.cred.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/university.cred.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-university --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-university.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-university.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-university.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-university.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/university.cred.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy university's CA cert to university's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.cred.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.cred.com/msp/tlscacerts/ca.crt"

  # Copy university's CA cert to university's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.cred.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.cred.com/tlsca/tlsca.university.cred.com-cert.pem"

  # Copy university's CA cert to university's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.cred.com/ca"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.cred.com/ca/ca.university.cred.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-university --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-university --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-university --id.name universityadmin --id.secret universityadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls" --enrollment.profile tls --csr.hosts peer0.university.cred.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/university.cred.com/peers/peer0.university.cred.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.cred.com/users/User1@university.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.cred.com/users/User1@university.cred.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://universityadmin:universityadminpw@localhost:7054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.cred.com/users/Admin@university.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.cred.com/users/Admin@university.cred.com/msp/config.yaml"
}

function createStudent() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/student.cred.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/student.cred.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-student --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-student.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-student.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-student.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-student.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/student.cred.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy student's CA cert to student's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/student.cred.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/student/ca-cert.pem" "${PWD}/organizations/peerOrganizations/student.cred.com/msp/tlscacerts/ca.crt"

  # Copy student's CA cert to student's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/student.cred.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/student/ca-cert.pem" "${PWD}/organizations/peerOrganizations/student.cred.com/tlsca/tlsca.student.cred.com-cert.pem"

  # Copy student's CA cert to student's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/student.cred.com/ca"
  cp "${PWD}/organizations/fabric-ca/student/ca-cert.pem" "${PWD}/organizations/peerOrganizations/student.cred.com/ca/ca.student.cred.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-student --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-student --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-student --id.name studentadmin --id.secret studentadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-student -M "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/student.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-student -M "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls" --enrollment.profile tls --csr.hosts peer0.student.cred.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/student.cred.com/peers/peer0.student.cred.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-student -M "${PWD}/organizations/peerOrganizations/student.cred.com/users/User1@student.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/student.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/student.cred.com/users/User1@student.cred.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://studentadmin:studentadminpw@localhost:8054 --caname ca-student -M "${PWD}/organizations/peerOrganizations/student.cred.com/users/Admin@student.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/student/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/student.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/student.cred.com/users/Admin@student.cred.com/msp/config.yaml"
}


function createCompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/company.cred.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/company.cred.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-company --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-company.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-company.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-company.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-company.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/company.cred.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy company's CA cert to company's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.cred.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.cred.com/msp/tlscacerts/ca.crt"

  # Copy company's CA cert to company's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.cred.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.cred.com/tlsca/tlsca.company.cred.com-cert.pem"

  # Copy company's CA cert to company's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.cred.com/ca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.cred.com/ca/ca.company.cred.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-company --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-company --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-company --id.name companyadmin --id.secret companyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls" --enrollment.profile tls --csr.hosts peer0.company.cred.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/company.cred.com/peers/peer0.company.cred.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.cred.com/users/User1@company.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.cred.com/users/User1@company.cred.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://companyadmin:companyadminpw@localhost:11054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.cred.com/users/Admin@company.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.cred.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.cred.com/users/Admin@company.cred.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/cred.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/cred.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/cred.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cred.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/cred.com/msp/tlscacerts/tlsca.cred.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cred.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/cred.com/tlsca/tlsca.cred.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/cred.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls" --enrollment.profile tls --csr.hosts orderer.cred.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/cred.com/orderers/orderer.cred.com/msp/tlscacerts/tlsca.cred.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cred.com/users/Admin@cred.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/cred.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/cred.com/users/Admin@cred.com/msp/config.yaml"
}

createUniversity
createStudent
createCompany
createOrderer